### ISSUE TITLE
2016/06/27 视频重力旋转的文章 逻辑有纰漏.

### ISSUE THREAD

**Issue by imknown** [imknown/IMKDevelopmentDaily#1]
https://github.com/imknown/IMKDevelopmentDaily/blob/master/2016/06/27_视频根据重力旋转与手动全屏的坑.md

如果 是 横屏进入此视频旋转页, 逻辑不对.

**Comment by tinkernels** [comment]
still not fixed?

**Comment by imknown** [comment]
@don-johnny Yes, the bug is still there. However, there are many more better repos doing this, anyway.
