### ISSUE TITLE
android 原型设计 跨平台 单位换算 技术参考能增加一个4k到8k的科普吗

### ISSUE THREAD

**Issue by Anr-C** [imknown/IMKDevelopmentDaily#5]
https://github.com/imknown/IMKDevelopmentDaily/blob/master/2016/11/12_android%20%E5%8E%9F%E5%9E%8B%E8%AE%BE%E8%AE%A1%20%E8%B7%A8%E5%B9%B3%E5%8F%B0%20%E5%8D%95%E4%BD%8D%E6%8D%A2%E7%AE%97%20%E6%8A%80%E6%9C%AF%E5%8F%82%E8%80%83.md

如上，2016到2019 有点久了哟~ 手动滑稽

**Comment by imknown** [comment]
好的, 有时间我会补充上 `高分屏` 和 `全面屏`.

**Comment by Anr-C** [comment]
ok, 厉害了哦

**Comment by imknown** [comment]
@TIL-MICE 改了一版, 还会修订的.
> https://github.com/imknown/IMKDevelopmentDaily/commit/cf19fe5466e236d7da7229adad0794dd0028fd6f
